import type { ActivityEvent, Candidate, Company, CompanyRole, HiringSettings, Job, Page, RolePermission } from "./types";

export const rolePermissions: Record<CompanyRole, RolePermission> = {
  "Super Admin": {
    label: "Single company owner",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: true,
    canTransferSuperAdmin: true,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: true,
  },
  Admin: {
    label: "Full access except admin control",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
  User: {
    label: "Hiring access",
    canEditCompany: false,
    canManageTeam: false,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
};

export const initialCompany: Company = {
  name: "TalentBank",
  industry: "HR technology",
  location: "Kuala Lumpur",
  size: "51-200",
  description: "Career discovery and hiring intelligence for modern teams.",
};

export const initialJobs: Job[] = [
  {
    id: 1,
    title: "Senior Product Lead",
    department: "product",
    status: "Open",
    location: "Kuala Lumpur",
    workMode: "Hybrid",
    salary: "RM 18k-28k",
    skills: ["Marketplace", "B2B SaaS", "Discovery"],
    screeningQuestion: "Tell us about a marketplace or B2B discovery decision you led.",
    applicants: 24,
    shortlisted: 2,
    hired: 0,
    expiresIn: 18,
  },
  {
    id: 2,
    title: "Growth Product Designer",
    department: "design",
    status: "Open",
    location: "Remote",
    workMode: "Remote",
    salary: "RM 12k-18k",
    skills: ["Activation", "Design systems", "Research"],
    screeningQuestion: "Share a growth or activation redesign and how you measured success.",
    applicants: 0,
    shortlisted: 0,
    hired: 0,
    expiresIn: 30,
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: 1,
    jobId: 1,
    name: "Maya Tan",
    title: "Product Lead, Fintech Marketplace",
    location: "Kuala Lumpur",
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 97,
    projectRelevance: 94,
    experience: 92,
    trajectory: 90,
    livingCv: "Verified",
    tags: ["Marketplace", "B2B", "Pricing"],
    evidence: [
      "Scaled a two-sided marketplace from 11k to 84k monthly active users.",
      "Has led hiring loops for product managers and analysts.",
      "Compensation is aligned with the current band.",
    ],
  },
  {
    id: 2,
    jobId: 1,
    name: "Irfan Rahman",
    title: "Senior PM, HR Tech",
    location: "Singapore",
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 91,
    projectRelevance: 89,
    experience: 88,
    trajectory: 86,
    livingCv: "Updated",
    tags: ["HR Tech", "AI workflows", "Enterprise"],
    evidence: [
      "Built AI-assisted recruiter workflows with measurable time-to-hire gains.",
      "Strong enterprise fluency, less direct consumer growth ownership.",
      "Needs relocation and package discussion before panel.",
    ],
  },
  {
    id: 3,
    jobId: 1,
    name: "Alya Hassan",
    title: "Growth Product Designer",
    location: "Kuala Lumpur",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 93,
    projectRelevance: 91,
    experience: 87,
    trajectory: 92,
    livingCv: "Verified",
    tags: ["Activation", "Design systems", "Research"],
    evidence: [
      "Lifted profile completion by 22% through activation redesign.",
      "Was shortlisted by this company before but has not applied to this job.",
      "Portfolio shows strong candidate and recruiter workflow instincts.",
    ],
  },
  {
    id: 4,
    jobId: 1,
    name: "Daniel Ong",
    title: "Principal Product Manager",
    location: "Remote",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 82,
    projectRelevance: 84,
    experience: 90,
    trajectory: 83,
    livingCv: "Stale",
    tags: ["0-1", "Discovery", "PLG"],
    evidence: [
      "Crisp written case study and strong discovery craft.",
      "Less evidence around regulated marketplace constraints.",
      "Available quickly and motivated by the mission.",
    ],
  },
];

export const initialHiringSettings: HiringSettings = {
  scoreWeights: {
    skill: 35,
    project: 30,
    experience: 20,
    trajectory: 15,
  },
  expiry: {
    countdown: true,
    promptResult: true,
    stayOpenAfterHire: true,
    autoCloseAfterHireDays: 30,
  },
  validation: {
    duplicateTitle: true,
    requireDepartment: true,
    logActions: true,
  },
  templates: {
    interview: {
      subject: "Next stage invitation: {{stageType}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nThank you for your interest in the {{role}} role. We would like to invite you to the next stage: {{stageType}}.\n\nTime: {{selectedSlot}}\nLocation: {{meetingLink}}\n\nPlease bring any questions about the team, role scope, and hiring process.\n\nBest,\n{{sender}}",
      includeLogo: true,
      stageType: "Online interview",
      dateTime: "{{selectedSlot}}",
      location: "{{meetingLink}}",
    },
    hired: {
      subject: "Hiring update from {{company}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nCongratulations. We are excited to move forward with you for the {{role}} role at {{company}}.\n\nNext step: {{nextStep}}.\n\nProposed start date: {{startDate}}.\n\nBest,\n{{sender}}",
      includeLogo: true,
      startDate: "{{startDate}}",
      nextStep: "{{onboardingStep}}",
    },
  },
};

export const initialActivity: ActivityEvent[] = [
  { id: 1, label: "Maya Tan shortlisted for Senior Product Lead", time: "2h ago", tone: "pink" },
  { id: 2, label: "Alya Hassan flagged for re-engagement", time: "Today", tone: "amber" },
  { id: 3, label: "Senior Product Lead expires in 18 days", time: "Job timer", tone: "zinc" },
];

export const navItems: Array<{ page: Page; label: string }> = [
  { page: "dashboard", label: "Dashboard" },
  { page: "jobs", label: "Jobs" },
  { page: "team", label: "Team" },
  { page: "profile", label: "Profile" },
  { page: "settings", label: "Settings" },
];
