import type {
  CareerEdge,
  CareerMapState,
  CareerNodeData,
  GeneratedScenario,
} from "./types";

function node(input: CareerNodeData): CareerNodeData {
  return input;
}

const sharedAnalytics = {
  requiredSkills: ["SQL", "Data cleaning", "Business metrics", "Analytical reasoning"],
  tools: ["Excel", "SQL", "Power BI", "Python"],
  certifications: ["Power BI Data Analyst", "SQL portfolio certificate"],
  portfolioEvidence: ["Dashboard case study", "Before/after metric insight", "Cleaned dataset walkthrough"],
  transferableSkills: ["Problem solving", "Pattern recognition", "Structured communication"],
  missingSkills: ["Stakeholder storytelling", "Advanced dashboard design"],
  nextActions: ["Build one dashboard project", "Document business decisions from analysis", "Practise presenting findings"],
};

export const initialMapState: CareerMapState = {
  nodes: {
    current: node({
      id: "current",
      title: "Data Science Student",
      roleType: "Current profile",
      nodeType: "current",
      x: 80,
      y: 280,
      timeline: "Now",
      difficulty: "Low",
      match: 100,
      summary: "Your current profile combines computer science foundations, analytics projects, and early portfolio evidence.",
      suitability: "This is the launch point. CareerOS uses your skills, interests, and evidence to branch into realistic early career options.",
      ...sharedAnalytics,
    }),
    dataAnalyst: node({
      id: "dataAnalyst",
      title: "Data Analyst",
      roleType: "Recommended role",
      nodeType: "recommended",
      x: 420,
      y: 90,
      timeline: "0-12 months",
      difficulty: "Medium",
      match: 88,
      summary: "A practical first role focused on cleaning, analysing, and explaining business data.",
      suitability: "This path suits you if you want a clear entry point into analytics while building stronger stakeholder exposure.",
      ...sharedAnalytics,
      missingSkills: ["Dashboard storytelling", "Business requirements gathering"],
      nextActions: ["Strengthen SQL", "Create an insight-focused case study", "Apply to graduate analyst roles"],
    }),
    biAnalyst: node({
      id: "biAnalyst",
      title: "Business Intelligence Analyst",
      roleType: "Recommended role",
      nodeType: "recommended",
      x: 420,
      y: 250,
      timeline: "12-18 months",
      difficulty: "Medium",
      match: 92,
      summary: "A dashboard and reporting path that turns data into decisions for business teams.",
      suitability: "This path is suitable if you enjoy analytical problem-solving and business reporting. Prioritise SQL, dashboard storytelling, and Power BI portfolio evidence.",
      ...sharedAnalytics,
      requiredSkills: ["SQL", "Dashboard storytelling", "Business reporting", "Data modelling"],
      tools: ["Power BI", "SQL", "Excel", "DAX"],
      missingSkills: ["Power BI storytelling", "Stakeholder communication"],
      nextActions: ["Build a Power BI dashboard", "Write a business-facing insight summary", "Apply to junior BI roles"],
    }),
    mlIntern: node({
      id: "mlIntern",
      title: "Machine Learning Intern",
      roleType: "Recommended role",
      nodeType: "recommended",
      x: 420,
      y: 410,
      timeline: "0-12 months",
      difficulty: "High",
      match: 78,
      summary: "A technical route into modelling, experimentation, and applied machine learning support work.",
      suitability: "This path works if you want deeper technical depth and are willing to build stronger statistics and model evaluation evidence.",
      ...sharedAnalytics,
      requiredSkills: ["Python", "Statistics", "Model evaluation", "Feature engineering"],
      tools: ["Python", "Jupyter", "Scikit-learn", "Git"],
      missingSkills: ["Production ML", "Experiment design"],
      nextActions: ["Publish one ML notebook", "Explain model trade-offs", "Apply for ML internships"],
    }),
    productAnalyst: node({
      id: "productAnalyst",
      title: "Product Analyst",
      roleType: "Recommended role",
      nodeType: "recommended",
      x: 420,
      y: 570,
      timeline: "12-24 months",
      difficulty: "Medium",
      match: 81,
      summary: "A product-focused analytics path where user behaviour, funnels, and experiments guide decisions.",
      suitability: "This path suits you if you enjoy connecting data with user behaviour and product decisions.",
      ...sharedAnalytics,
      requiredSkills: ["Product metrics", "Experiment analysis", "SQL", "User behaviour analysis"],
      tools: ["Amplitude", "Looker", "SQL", "Sheets"],
      missingSkills: ["Experiment design", "Product thinking"],
      nextActions: ["Analyse a product funnel", "Write a product insight memo", "Study activation metrics"],
    }),
    seniorDataAnalyst: node({
      id: "seniorDataAnalyst",
      title: "Senior Data Analyst",
      roleType: "Future role",
      nodeType: "future",
      x: 780,
      y: 90,
      timeline: "2-4 years",
      difficulty: "Medium",
      match: 84,
      summary: "Owns complex analysis, stakeholder questions, and reusable reporting logic.",
      suitability: "A strong next step when you can frame business questions and lead analysis without close supervision.",
      ...sharedAnalytics,
      nextActions: ["Lead a stakeholder analysis", "Mentor a junior analyst", "Build reusable reporting templates"],
    }),
    seniorBiAnalyst: node({
      id: "seniorBiAnalyst",
      title: "Senior BI Analyst",
      roleType: "Future role",
      nodeType: "future",
      x: 780,
      y: 250,
      timeline: "2-4 years",
      difficulty: "Medium",
      match: 82,
      summary: "Leads BI reporting systems, metric definitions, and dashboard quality.",
      suitability: "This becomes realistic once you can connect executive questions to reliable BI systems.",
      ...sharedAnalytics,
      requiredSkills: ["Metric design", "Dashboard governance", "DAX", "Stakeholder management"],
      nextActions: ["Own a recurring dashboard", "Document metric definitions", "Present dashboard recommendations"],
    }),
    juniorDataScientist: node({
      id: "juniorDataScientist",
      title: "Junior Data Scientist",
      roleType: "Future role",
      nodeType: "future",
      x: 780,
      y: 410,
      timeline: "1-3 years",
      difficulty: "High",
      match: 76,
      summary: "Supports modelling, experimentation, and data science delivery.",
      suitability: "This route needs stronger statistics, model interpretation, and production awareness.",
      ...sharedAnalytics,
      requiredSkills: ["Statistics", "Python", "Machine learning", "Experiment design"],
      missingSkills: ["Model deployment", "Advanced statistics"],
    }),
    growthAnalyst: node({
      id: "growthAnalyst",
      title: "Growth Product Analyst",
      roleType: "Future role",
      nodeType: "future",
      x: 780,
      y: 570,
      timeline: "2-3 years",
      difficulty: "Medium",
      match: 79,
      summary: "Uses product data to improve activation, retention, and revenue loops.",
      suitability: "Good if you want a more commercial path with experimentation and product decision-making.",
      ...sharedAnalytics,
      requiredSkills: ["Funnel analysis", "A/B testing", "Product strategy", "SQL"],
    }),
    dataScientist: node({
      id: "dataScientist",
      title: "Data Scientist",
      roleType: "Future role",
      nodeType: "future",
      x: 1130,
      y: 410,
      timeline: "3-5 years",
      difficulty: "High",
      match: 72,
      summary: "Builds models and experiments that solve complex business or product problems.",
      suitability: "Best after you prove modelling quality and can explain trade-offs to stakeholders.",
      ...sharedAnalytics,
      requiredSkills: ["Machine learning", "Statistics", "Python", "Causal thinking"],
      tools: ["Python", "Scikit-learn", "SQL", "Cloud notebooks"],
      criteria: "Best after you can explain model trade-offs and show reliable modelling evidence.",
      skillFocus: "Machine learning, statistics, causal thinking, and model communication.",
      workStyle: "Deep analytical work with business translation.",
      careerOutcome: "A technical IC route that can later branch into senior IC, engineering, product, or leadership.",
      tradeOff: "More technical depth and ambiguity than BI or product analytics paths.",
    }),
    mlEngineer: node({
      id: "mlEngineer",
      title: "Machine Learning Engineer",
      roleType: "Specialist path",
      nodeType: "future",
      x: 1480,
      y: 580,
      timeline: "3-5 years",
      difficulty: "Very High",
      match: 66,
      summary: "Turns models into reliable production systems and deployment pipelines.",
      suitability: "Best if you prefer engineering systems, model deployment, and infrastructure over pure analysis.",
      ...sharedAnalytics,
      requiredSkills: ["Python engineering", "MLOps", "APIs", "Cloud deployment"],
      tools: ["Python", "Docker", "Cloud services", "GitHub Actions"],
      missingSkills: ["Software engineering depth", "Deployment patterns"],
      nextActions: ["Build a deployed model demo", "Study APIs", "Pair with engineering projects"],
      criteria: "Choose this if you want models to become production systems rather than analysis artifacts.",
      skillFocus: "MLOps, APIs, cloud deployment, and software engineering habits.",
      workStyle: "Engineering-heavy build work with reliability and system ownership.",
      careerOutcome: "A specialist technical path toward ML platform or applied ML engineering roles.",
      tradeOff: "Higher engineering bar and less pure analysis or stakeholder storytelling.",
    }),
    aiEngineer: node({
      id: "aiEngineer",
      title: "AI Engineer",
      roleType: "Skill-heavy path",
      nodeType: "future",
      x: 1480,
      y: 740,
      timeline: "3-5 years",
      difficulty: "Very High",
      match: 64,
      summary: "Builds AI-assisted products, workflows, and applied model integrations.",
      suitability: "Good for users who enjoy building prototypes and turning models into usable product features.",
      ...sharedAnalytics,
      requiredSkills: ["LLM workflows", "Prompt evaluation", "APIs", "Product judgement"],
      tools: ["Python", "Vector databases", "API clients", "Evaluation sheets"],
      missingSkills: ["AI product evaluation", "Systems integration"],
      nextActions: ["Build an AI workflow prototype", "Document evaluation criteria", "Ship a small demo"],
      criteria: "Choose this if you enjoy turning AI capabilities into usable product workflows.",
      skillFocus: "LLM workflows, evaluation, APIs, and product judgement.",
      workStyle: "Prototype-driven building with fast iteration and product ambiguity.",
      careerOutcome: "A modern applied AI path toward AI product engineering or workflow automation.",
      tradeOff: "Fast-changing tools require continuous upskilling and careful evaluation discipline.",
    }),
    productDataScientist: node({
      id: "productDataScientist",
      title: "Product Data Scientist",
      roleType: "Cross-functional path",
      nodeType: "future",
      x: 1480,
      y: 900,
      timeline: "3-5 years",
      difficulty: "High",
      match: 73,
      summary: "Uses experimentation and product behaviour data to guide product decisions.",
      suitability: "A strong branch if you like both modelling and user/product decision-making.",
      ...sharedAnalytics,
      requiredSkills: ["Experiment design", "Causal thinking", "Product metrics", "Stakeholder influence"],
      tools: ["SQL", "Amplitude", "Python", "Experiment dashboards"],
      missingSkills: ["Product intuition", "Experiment communication"],
      nextActions: ["Analyse one product funnel", "Write an experiment memo", "Study retention metrics"],
      criteria: "Choose this if product behaviour and decision support feel more energising than pure modelling.",
      skillFocus: "Experiment design, product metrics, causal thinking, and stakeholder influence.",
      workStyle: "Cross-functional product work with frequent communication.",
      careerOutcome: "A hybrid route into product analytics leadership or data product strategy.",
      tradeOff: "Less deep modelling time; more meetings, prioritisation, and product ambiguity.",
    }),
    seniorDataScientist: node({
      id: "seniorDataScientist",
      title: "Senior Data Scientist",
      roleType: "Leadership track",
      nodeType: "future",
      x: 1480,
      y: 420,
      timeline: "4-6 years",
      difficulty: "High",
      match: 70,
      summary: "Owns higher-impact modelling work, technical judgement, and mentoring across projects.",
      suitability: "This branch fits if you want deeper technical credibility before moving into strategy or people leadership.",
      ...sharedAnalytics,
      requiredSkills: ["Advanced modelling", "Experiment design", "Technical mentoring", "Model communication"],
      tools: ["Python", "SQL", "Experiment notebooks", "Model review docs"],
      missingSkills: ["Technical leadership examples", "Advanced statistical judgement"],
      nextActions: ["Lead one modelling case study", "Document model trade-offs", "Mentor a peer on analysis quality"],
      criteria: "Choose this if you want deeper senior IC credibility before managing teams.",
      skillFocus: "Advanced modelling, experiment design, technical mentoring, and model review.",
      workStyle: "High-autonomy technical ownership with mentoring.",
      careerOutcome: "A senior individual contributor route toward lead data scientist or principal-level work.",
      tradeOff: "Requires stronger technical judgement and proof of impact across ambiguous projects.",
    }),
    researchScientist: node({
      id: "researchScientist",
      title: "Research Scientist",
      roleType: "Research path",
      nodeType: "future",
      x: 1480,
      y: 1060,
      timeline: "5-8 years",
      difficulty: "Very High",
      match: 55,
      summary: "Focuses on deeper methods, publications, and novel technical work.",
      suitability: "A more academic branch for users who enjoy depth, ambiguity, and long research cycles.",
      ...sharedAnalytics,
      requiredSkills: ["Research methods", "Advanced statistics", "Paper reading", "Experiment design"],
      missingSkills: ["Research portfolio", "Advanced mathematical depth"],
      nextActions: ["Replicate one paper", "Document research notes", "Consider postgraduate study"],
      criteria: "Choose this if you are motivated by depth, novelty, and long research cycles.",
      skillFocus: "Research methods, advanced statistics, paper reading, and experimental design.",
      workStyle: "Deep focus, ambiguity, and rigorous experimentation.",
      careerOutcome: "A research-heavy route toward applied research, postgraduate study, or specialist labs.",
      tradeOff: "Slower feedback loops and a higher bar for mathematical or research evidence.",
    }),
    dataScienceConsultant: node({
      id: "dataScienceConsultant",
      title: "Data Science Consultant",
      roleType: "Consulting path",
      nodeType: "business",
      x: 1480,
      y: 1220,
      timeline: "4-7 years",
      difficulty: "High",
      match: 67,
      summary: "Applies data science judgement to client problems, discovery, and solution design.",
      suitability: "A strong option if you like variety, business framing, and translating technical work into decisions for clients.",
      ...sharedAnalytics,
      requiredSkills: ["Client discovery", "Model scoping", "Solution storytelling", "Commercial judgement"],
      tools: ["Python", "Slides", "SQL", "Discovery notes"],
      missingSkills: ["Consulting communication", "Client management"],
      nextActions: ["Write a consulting-style model proposal", "Build a client-ready case study", "Practise explaining trade-offs"],
      criteria: "Choose this if client variety and business framing appeal more than one internal roadmap.",
      skillFocus: "Client discovery, model scoping, solution storytelling, and commercial judgement.",
      workStyle: "Client-facing project variety with more presentations and context switching.",
      careerOutcome: "A flexible consulting route toward advisory, freelance, or data strategy work.",
      tradeOff: "More sales and client management pressure, less predictable technical depth.",
    }),
    analyticsManager: node({
      id: "analyticsManager",
      title: "Analytics Manager",
      roleType: "Future role",
      nodeType: "future",
      x: 1480,
      y: 260,
      timeline: "4-6 years",
      difficulty: "High",
      match: 75,
      summary: "Leads analysts, prioritises reporting work, and shapes analytics decision rhythms.",
      suitability: "A realistic management step if you combine BI craft with stakeholder leadership.",
      ...sharedAnalytics,
      requiredSkills: ["People leadership", "Roadmapping", "Analytics strategy", "Executive communication"],
      missingSkills: ["Team management", "Prioritisation under ambiguity"],
      criteria: "Choose this if you want your data work to influence teams, priorities, and decision rhythms.",
      skillFocus: "People leadership, roadmapping, analytics strategy, and executive communication.",
      workStyle: "Stakeholder-heavy leadership with prioritisation and coaching.",
      careerOutcome: "A management route toward Head of Data or analytics leadership.",
      tradeOff: "Less hands-on modelling and more ambiguity, meetings, and people responsibility.",
    }),
    leadDataScientist: node({
      id: "leadDataScientist",
      title: "Lead Data Scientist",
      roleType: "Future role",
      nodeType: "future",
      x: 1840,
      y: 420,
      timeline: "5-7 years",
      difficulty: "Very High",
      match: 68,
      summary: "Guides data science strategy, model quality, and technical direction.",
      suitability: "This path requires deep technical judgement and the ability to guide others through uncertainty.",
      ...sharedAnalytics,
      requiredSkills: ["Technical leadership", "ML systems", "Research judgement", "Mentoring"],
      missingSkills: ["Technical leadership proof", "Production ML depth"],
    }),
    headOfData: node({
      id: "headOfData",
      title: "Head of Data",
      roleType: "Future role",
      nodeType: "future",
      x: 1840,
      y: 260,
      timeline: "6-8 years",
      difficulty: "Very High",
      match: 70,
      summary: "Owns data strategy, team direction, governance, and business impact.",
      suitability: "A leadership path for when your analytics work becomes organisation-level decision infrastructure.",
      ...sharedAnalytics,
      requiredSkills: ["Data strategy", "Hiring", "Governance", "Executive influence"],
      missingSkills: ["Leadership portfolio", "Cross-functional strategy"],
    }),
    freelanceConsultant: node({
      id: "freelanceConsultant",
      title: "Freelance Dashboard Consultant",
      roleType: "Business path",
      nodeType: "business",
      x: 1130,
      y: 20,
      timeline: "2-4 years",
      difficulty: "High",
      match: 74,
      summary: "Turns BI and dashboard skill into client-facing project work.",
      suitability: "Good if you want independence and can sell outcomes, not only analysis.",
      ...sharedAnalytics,
      requiredSkills: ["Client discovery", "Dashboard delivery", "Pricing", "Communication"],
      missingSkills: ["Sales confidence", "Client portfolio"],
    }),
    consultancyFounder: node({
      id: "consultancyFounder",
      title: "Data Consultancy Founder",
      roleType: "Business path",
      nodeType: "business",
      x: 1480,
      y: 20,
      timeline: "4-7 years",
      difficulty: "Very High",
      match: 66,
      summary: "Builds a service business around analytics, BI, or data strategy.",
      suitability: "This becomes realistic after you can repeatedly deliver client outcomes and manage commercial risk.",
      ...sharedAnalytics,
      requiredSkills: ["Sales", "Delivery systems", "Hiring", "Client retention"],
      missingSkills: ["Business operations", "Lead generation"],
    }),
    biProductManager: node({
      id: "biProductManager",
      title: "Data Product Manager",
      roleType: "Cross-functional path",
      nodeType: "future",
      x: 1130,
      y: 180,
      timeline: "4-6 years",
      difficulty: "High",
      match: 72,
      summary: "Shapes internal data products, metric systems, and analytics platform priorities.",
      suitability: "Good if you enjoy stakeholder alignment and product decisions more than building every dashboard yourself.",
      ...sharedAnalytics,
      requiredSkills: ["Roadmapping", "Data product thinking", "Stakeholder discovery", "Prioritisation"],
      missingSkills: ["Product strategy", "Influence without authority"],
      nextActions: ["Write a data product brief", "Interview internal dashboard users", "Define success metrics"],
    }),
    reportingOpsLead: node({
      id: "reportingOpsLead",
      title: "Reporting Operations Lead",
      roleType: "Lower-stress path",
      nodeType: "future",
      x: 1130,
      y: 340,
      timeline: "3-5 years",
      difficulty: "Medium",
      match: 78,
      summary: "Builds stable reporting rhythms, documentation, and internal analytics support.",
      suitability: "A calmer branch for users who prefer predictable operations and quality over high-ambiguity strategy.",
      ...sharedAnalytics,
      requiredSkills: ["Documentation", "Reporting QA", "Process design", "Stakeholder support"],
      missingSkills: ["Process ownership", "Service design"],
      nextActions: ["Document a reporting process", "Create a dashboard QA checklist", "Improve one recurring report"],
    }),
    businessConsultant: node({
      id: "businessConsultant",
      title: "Business Consultant",
      roleType: "Consulting path",
      nodeType: "business",
      x: 780,
      y: 710,
      timeline: "2-4 years",
      difficulty: "High",
      match: 76,
      summary: "Uses analysis, facilitation, and business framing to solve client or internal problems.",
      suitability: "A better branch if you want variety, client exposure, and less time in technical tooling.",
      ...sharedAnalytics,
      requiredSkills: ["Problem framing", "Presentation", "Client discovery", "Business cases"],
      tools: ["Slides", "Excel", "Research notes", "Workshop boards"],
      missingSkills: ["Executive communication", "Commercial judgement"],
      nextActions: ["Write a consulting-style case memo", "Practise presenting trade-offs", "Study business models"],
    }),
  },
  edges: [
    { id: "e-current-dataAnalyst", from: "current", to: "dataAnalyst" },
    { id: "e-current-biAnalyst", from: "current", to: "biAnalyst" },
    { id: "e-current-mlIntern", from: "current", to: "mlIntern" },
    { id: "e-current-productAnalyst", from: "current", to: "productAnalyst" },
    { id: "e-dataAnalyst-seniorDataAnalyst", from: "dataAnalyst", to: "seniorDataAnalyst" },
    { id: "e-biAnalyst-seniorBiAnalyst", from: "biAnalyst", to: "seniorBiAnalyst" },
    { id: "e-mlIntern-juniorDataScientist", from: "mlIntern", to: "juniorDataScientist" },
    { id: "e-productAnalyst-growthAnalyst", from: "productAnalyst", to: "growthAnalyst" },
    { id: "e-juniorDataScientist-dataScientist", from: "juniorDataScientist", to: "dataScientist" },
    { id: "e-dataScientist-mlEngineer", from: "dataScientist", to: "mlEngineer" },
    { id: "e-dataScientist-aiEngineer", from: "dataScientist", to: "aiEngineer" },
    { id: "e-dataScientist-productDataScientist", from: "dataScientist", to: "productDataScientist" },
    { id: "e-dataScientist-seniorDataScientist", from: "dataScientist", to: "seniorDataScientist" },
    { id: "e-dataScientist-researchScientist", from: "dataScientist", to: "researchScientist" },
    { id: "e-dataScientist-dataScienceConsultant", from: "dataScientist", to: "dataScienceConsultant" },
    { id: "e-seniorBiAnalyst-analyticsManager", from: "seniorBiAnalyst", to: "analyticsManager" },
    { id: "e-seniorBiAnalyst-biProductManager", from: "seniorBiAnalyst", to: "biProductManager" },
    { id: "e-seniorBiAnalyst-reportingOpsLead", from: "seniorBiAnalyst", to: "reportingOpsLead" },
    { id: "e-seniorDataScientist-leadDataScientist", from: "seniorDataScientist", to: "leadDataScientist" },
    { id: "e-dataScientist-analyticsManager", from: "dataScientist", to: "analyticsManager" },
    { id: "e-analyticsManager-headOfData", from: "analyticsManager", to: "headOfData" },
    { id: "e-seniorDataAnalyst-freelanceConsultant", from: "seniorDataAnalyst", to: "freelanceConsultant" },
    { id: "e-seniorDataAnalyst-businessConsultant", from: "seniorDataAnalyst", to: "businessConsultant" },
    { id: "e-freelanceConsultant-consultancyFounder", from: "freelanceConsultant", to: "consultancyFounder" },
  ],
};

export const baseExpandedNodes = new Set(["current"]);

export function generateScenarioBranch(
  scenario: string,
  startNode: CareerNodeData,
  index: number,
): GeneratedScenario {
  const lower = scenario.toLowerCase();
  const id = `scenario-${Date.now()}-${index}`;
  const isCulinary = lower.includes("culinary") || lower.includes("food") || lower.includes("chef");
  const isBusiness = lower.includes("business") || lower.includes("consult") || lower.includes("founder");
  const isUx = lower.includes("ux") || lower.includes("design");
  const isProductManagement = lower.includes("product management") || lower.includes("product manager");
  const isManagement = lower.includes("management") || lower.includes("manager") || lower.includes("lead");
  const isLowerStress = lower.includes("lower-stress") || lower.includes("lower stress") || lower.includes("less stress");
  const isStartup = lower.includes("startup") || lower.includes("own company");
  const isConsultancy = lower.includes("consultancy") || lower.includes("consultant") || lower.includes("consulting");
  const laneY = Math.max(startNode.y + 280, 1500 + index * 170);

  const sequence = isCulinary
    ? ["Culinary Business Research", "Weekend Culinary Course", "Food Business Validation", "Pop-up Food Project", "Culinary Entrepreneur"]
    : isUx
      ? ["UX Research Assistant", "Product Research Portfolio", "Junior UX Designer", "UX Product Designer"]
      : isProductManagement
        ? ["Associate Product Manager", "Product Manager"]
      : isConsultancy || isBusiness || isStartup
        ? ["Freelance Dashboard Consultant", "Client Portfolio", "Data Consultancy Founder"]
        : isManagement
          ? ["Senior Analyst", "Analytics Lead", "Analytics Manager", "Head of Data"]
          : isLowerStress
            ? ["Reporting Analyst", "Operations Analyst", "Process Improvement Lead"]
            : ["Exploratory Branch", "Skill Validation Sprint", "Portfolio Proof", "Target Role"];

  const nodes = sequence.map((title, step) => ({
    id: `${id}-${step}`,
    title,
    roleType: step === 0 ? "AI-generated branch" : "Stepping stone",
    nodeType: isCulinary || isUx ? "industry" : isConsultancy || isBusiness || isStartup ? "business" : step === 1 ? "skill" : "custom",
    x: startNode.x + 380 * (step + 1),
    y: laneY,
    timeline: step === 0 ? "0-6 months" : step < 3 ? "6-18 months" : "2-4 years",
    difficulty: isCulinary || isConsultancy || isBusiness || isStartup ? "High" : "Medium",
    match: Math.max(42, 76 - step * 7),
    riskLevel: isCulinary || isConsultancy || isBusiness || isStartup ? "High" : "Medium",
    summary: `AI-generated step for: ${scenario}`,
    suitability: isCulinary
      ? "Your research discipline transfers, but culinary craft and food operations need deliberate low-risk experiments."
      : isConsultancy || isBusiness
        ? "Your analytics skill can become a service, but client acquisition and delivery systems become the main challenge."
        : isProductManagement
          ? "This branch uses analytics credibility as a bridge into product decisions, prioritisation, and stakeholder leadership."
        : "This branch converts your existing profile into a new direction through staged proof instead of a sudden leap.",
    requiredSkills: isCulinary
      ? ["Customer research", "Food operations", "Costing", "Brand testing"]
      : isConsultancy || isBusiness
        ? ["Client discovery", "Pricing", "Delivery systems", "Sales"]
        : isProductManagement
          ? ["Product discovery", "Roadmapping", "Prioritisation", "Stakeholder communication"]
        : ["Research", "Communication", "Portfolio storytelling"],
    tools: ["CareerOS planner", "Portfolio evidence", "Feedback tracker"],
    certifications: isCulinary ? ["Weekend culinary course", "Food safety basics"] : ["Targeted short course"],
    portfolioEvidence: ["Experiment result", "Reflection note", "Proof-of-work milestone"],
    transferableSkills: ["Research", "Structured thinking", "Experiment design"],
    missingSkills: isCulinary ? ["Culinary craft", "Food operations"] : isConsultancy || isBusiness || isStartup ? ["Sales", "Client management"] : isProductManagement ? ["Product judgement", "Prioritisation"] : ["Domain credibility"],
    nextActions: ["Run a small experiment", "Capture evidence", "Review the branch after 30 days"],
    criteria: `Generated from the scenario: ${scenario}`,
    skillFocus: isCulinary
      ? "Culinary operations, customer research, costing, and validation."
      : isConsultancy || isBusiness || isStartup
        ? "Client discovery, pricing, delivery systems, and sales."
        : isProductManagement
          ? "Product discovery, prioritisation, metrics, and stakeholder influence."
          : "Domain credibility, communication, portfolio storytelling, and staged proof.",
    workStyle: isCulinary
      ? "Hands-on exploration with low-risk weekend experiments."
      : isConsultancy || isBusiness || isStartup
        ? "Independent, client-facing, commercially accountable work."
        : "Scenario-driven transition work with clear validation milestones.",
    careerOutcome: sequence[sequence.length - 1],
    tradeOff: isCulinary || isConsultancy || isBusiness || isStartup
      ? "High uncertainty; keep the first step small and evidence-backed."
      : "Medium uncertainty; proof-of-work reduces transition risk.",
    isCustom: true,
  })) satisfies CareerNodeData[];

  const edges: CareerEdge[] = nodes.map((item, step) => ({
    id: step === 0 ? `e-${startNode.id}-${item.id}` : `e-${nodes[step - 1].id}-${item.id}`,
    from: step === 0 ? startNode.id : nodes[step - 1].id,
    to: item.id,
    generated: true,
  }));

  return {
    title: sequence[sequence.length - 1],
    startNodeId: startNode.id,
    nodes,
    edges,
    note: `CareerOS generated a ${isCulinary ? "major industry jump" : isConsultancy || isBusiness ? "business branch" : "scenario branch"} from ${startNode.title}.`,
  };
}

export function getChildren(edges: CareerEdge[], nodeId: string) {
  return edges.filter((edge) => edge.from === nodeId).map((edge) => edge.to);
}

export function getAncestors(edges: CareerEdge[], nodeId: string) {
  const result = new Set<string>();
  let cursor = nodeId;
  while (cursor) {
    const parent = edges.find((edge) => edge.to === cursor)?.from;
    if (!parent || result.has(parent)) break;
    result.add(parent);
    cursor = parent;
  }
  return result;
}
