import { getCandidateLivingCv } from "@/lib/candidateLivingCvData";
import type { ActivityEvent, Candidate, Company, CompanyRole, HiringSettings, Job, Page, RolePermission, TeamMember } from "./types";

export const rolePermissions: Record<CompanyRole, RolePermission> = {
  "Super Admin": {
    label: "Single company owner",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: true,
    canTransferSuperAdmin: true,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: true,
  },
  Admin: {
    label: "Full access except admin control",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
  User: {
    label: "Hiring access",
    canEditCompany: false,
    canManageTeam: false,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
};

export const initialCompany: Company = {
  name: "TalentBank",
  industry: "HR technology",
  location: "Kuala Lumpur",
  size: "51-200",
  description: "Career discovery and hiring intelligence for modern teams.",
};

export const initialJobs: Job[] = [
  {
    id: 1,
    title: "Senior Product Lead",
    department: "product",
    status: "Open",
    location: "Kuala Lumpur",
    workMode: "Hybrid",
    employmentType: "Full-time",
    salary: "RM 18k-28k",
    description: "Lead product strategy for CareerOS hiring workflows and marketplace intelligence.",
    requirements: "Strong marketplace, B2B SaaS, discovery, and stakeholder leadership experience.",
    deadline: "2026-06-27",
    createdBy: "Shihong Wong",
    skills: ["Marketplace", "B2B SaaS", "Discovery"],
    screeningQuestion: "Tell us about a marketplace or B2B discovery decision you led.",
    applicants: 24,
    shortlisted: 2,
    hired: 0,
    expiresIn: 18,
  },
  {
    id: 2,
    title: "Growth Product Designer",
    department: "design",
    status: "Open",
    location: "Remote",
    workMode: "Remote",
    employmentType: "Full-time",
    salary: "RM 12k-18k",
    description: "Design growth systems that improve candidate and employer activation.",
    requirements: "Experience with activation, design systems, research, and product experimentation.",
    deadline: "2026-07-09",
    createdBy: "Sarah Lee",
    skills: ["Activation", "Design systems", "Research"],
    screeningQuestion: "Share a growth or activation redesign and how you measured success.",
    applicants: 0,
    shortlisted: 0,
    hired: 0,
    expiresIn: 30,
  },
];

export const initialMembers: TeamMember[] = [
  {
    id: 1,
    name: "Shihong Wong",
    email: "admin@talentbank.com",
    role: "Super Admin",
    status: "Active",
    presence: "Online",
    focus: "Workspace owner",
    lastActive: "Now",
    password: "careeros",
  },
  {
    id: 2,
    name: "Sarah Lee",
    email: "sarah@talentbank.com",
    role: "Admin",
    status: "Active",
    presence: "Offline",
    focus: "Hiring operations",
    lastActive: "2h ago",
    password: "careeros",
  },
  {
    id: 3,
    name: "Nadia Lim",
    email: "nadia@talentbank.com",
    role: "User",
    status: "Active",
    presence: "Online",
    focus: "Candidate review",
    lastActive: "18m ago",
    password: "careeros",
  },
  {
    id: 4,
    name: "Victor Chen",
    email: "victor@talentbank.com",
    role: "User",
    status: "Active",
    presence: "Offline",
    focus: "Leadership visibility",
    lastActive: "Yesterday",
    password: "careeros",
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: 1,
    jobId: 1,
    name: getCandidateLivingCv(1).name,
    title: getCandidateLivingCv(1).title,
    location: getCandidateLivingCv(1).location,
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 97,
    projectRelevance: 94,
    experience: 92,
    trajectory: 90,
    livingCv: "Verified",
    tags: [...getCandidateLivingCv(1).skills.technical.slice(0, 4), getCandidateLivingCv(1).direction],
    evidence: getCandidateLivingCv(1).employerEvidence,
    livingCvDetails: getCandidateLivingCv(1),
  },
  {
    id: 2,
    jobId: 1,
    name: "Irfan Rahman",
    title: "Senior PM, HR Tech",
    location: "Singapore",
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 91,
    projectRelevance: 89,
    experience: 88,
    trajectory: 86,
    livingCv: "Updated",
    tags: ["HR Tech", "AI workflows", "Enterprise"],
    evidence: getCandidateLivingCv(2).employerEvidence,
    livingCvDetails: getCandidateLivingCv(2),
  },
  {
    id: 3,
    jobId: 1,
    name: "Alya Hassan",
    title: "Growth Product Designer",
    location: "Kuala Lumpur",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 93,
    projectRelevance: 91,
    experience: 87,
    trajectory: 92,
    livingCv: "Verified",
    tags: ["Activation", "Design systems", "Research"],
    evidence: getCandidateLivingCv(3).employerEvidence,
    livingCvDetails: getCandidateLivingCv(3),
  },
  {
    id: 4,
    jobId: 1,
    name: "Daniel Ong",
    title: "Principal Product Manager",
    location: "Remote",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 82,
    projectRelevance: 84,
    experience: 90,
    trajectory: 83,
    livingCv: "Stale",
    tags: ["0-1", "Discovery", "PLG"],
    evidence: getCandidateLivingCv(4).employerEvidence,
    livingCvDetails: getCandidateLivingCv(4),
  },
];

export const initialHiringSettings: HiringSettings = {
  scoreWeights: {
    skill: 35,
    project: 30,
    experience: 20,
    trajectory: 15,
  },
  expiry: {
    countdown: true,
    promptResult: true,
    stayOpenAfterHire: true,
    autoCloseAfterHireDays: 30,
  },
  validation: {
    duplicateTitle: true,
    requireDepartment: true,
    logActions: true,
  },
  templates: {
    interview: {
      subject: "Next stage invitation: {{stageType}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nThank you for your interest in the {{role}} role. We would like to invite you to the next stage: {{stageType}}.\n\nTime: {{selectedSlot}}\nLocation: {{meetingLink}}\n\nPlease bring any questions about the team, role scope, and hiring process.\n\nBest,\n{{sender}}",
      includeLogo: true,
      stageType: "Online interview",
      dateTime: "{{selectedSlot}}",
      location: "{{meetingLink}}",
    },
    hired: {
      subject: "Hiring update from {{company}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nCongratulations. We are excited to move forward with you for the {{role}} role at {{company}}.\n\nNext step: {{nextStep}}.\n\nProposed start date: {{startDate}}.\n\nBest,\n{{sender}}",
      includeLogo: true,
      startDate: "{{startDate}}",
      nextStep: "{{onboardingStep}}",
    },
  },
};

export const initialActivity: ActivityEvent[] = [
  { id: 1, label: "Maya Tan shortlisted for Senior Product Lead", time: "2h ago", tone: "pink" },
  { id: 2, label: "Alya Hassan flagged for re-engagement", time: "Today", tone: "amber" },
  { id: 3, label: "Senior Product Lead expires in 18 days", time: "Job timer", tone: "zinc" },
];

export const navItems: Array<{ page: Page; label: string }> = [
  { page: "dashboard", label: "Dashboard" },
  { page: "jobs", label: "Jobs" },
  { page: "team", label: "Team" },
  { page: "profile", label: "Profile" },
  { page: "settings", label: "Settings" },
];
