import { getCandidateLivingCv } from "@/lib/candidateLivingCvData";
import type { ActivityEvent, Candidate, Company, CompanyRole, HiringSettings, Job, Page, Project, RolePermission, TeamMember } from "./types";

export const rolePermissions: Record<CompanyRole, RolePermission> = {
  "Super Admin": {
    label: "Single company owner",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: true,
    canTransferSuperAdmin: true,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: true,
  },
  Admin: {
    label: "Full access except admin control",
    canEditCompany: true,
    canManageTeam: true,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
  User: {
    label: "Hiring access",
    canEditCompany: false,
    canManageTeam: false,
    canManageAdmins: false,
    canTransferSuperAdmin: false,
    canManageJobs: true,
    canApproach: true,
    canMarkHired: true,
    canRemoveWorkspace: false,
  },
};

export const initialCompany: Company = {
  name: "TalentBank",
  industry: "HR technology",
  location: "Kuala Lumpur",
  size: "51-200",
  description: "Career discovery and hiring intelligence for modern teams.",
};

export const initialJobs: Job[] = [
  {
    id: 1,
    title: "Senior Product Lead",
    department: "product",
    status: "Open",
    location: "Kuala Lumpur",
    workMode: "Hybrid",
    employmentType: "Full-time",
    visibility: "open",
    targetUniversities: [],
    salary: "RM 18k-28k",
    description: "Lead product strategy for CareerOS hiring workflows and marketplace intelligence.",
    requirements: "Strong marketplace, B2B SaaS, discovery, and stakeholder leadership experience.",
    deadline: "2026-06-27",
    createdBy: "Shihong Wong",
    skills: ["Marketplace", "B2B SaaS", "Discovery"],
    screeningQuestion: "Tell us about a marketplace or B2B discovery decision you led.",
    applicants: 24,
    shortlisted: 2,
    hired: 0,
    expiresIn: 18,
    supervisorName: "Shihong Wong",
    supervisorAnimal: "lion",
  },
  {
    id: 2,
    title: "Growth Product Designer",
    department: "design",
    status: "Open",
    location: "Remote",
    workMode: "Remote",
    employmentType: "Full-time",
    visibility: "open",
    targetUniversities: [],
    salary: "RM 12k-18k",
    description: "Design growth systems that improve candidate and employer activation.",
    requirements: "Experience with activation, design systems, research, and product experimentation.",
    deadline: "2026-07-09",
    createdBy: "Sarah Lee",
    skills: ["Activation", "Design systems", "Research"],
    screeningQuestion: "Share a growth or activation redesign and how you measured success.",
    applicants: 3,
    shortlisted: 2,
    hired: 0,
    expiresIn: 30,
    supervisorName: "Sarah Lee",
    supervisorAnimal: "dolphin",
  },
  {
    id: 3,
    title: "Product Analytics Intern",
    department: "product",
    status: "Open",
    location: "Kuala Lumpur",
    workMode: "Hybrid",
    employmentType: "Internship",
    visibility: "collab",
    targetUniversities: ["Asia Pacific University", "Taylor's University"],
    salary: "RM 1.2k-1.8k/mo",
    description: "Support the product team with funnel analysis, candidate quality reporting, and dashboard experiments.",
    requirements: "Penultimate or final-year student comfortable with spreadsheets, SQL basics, and data storytelling.",
    deadline: "2026-08-15",
    createdBy: "Shihong Wong",
    skills: ["Analytics", "SQL", "Data storytelling"],
    screeningQuestion: "Tell us about a time you used data to change a decision.",
    applicants: 9,
    shortlisted: 1,
    hired: 0,
    expiresIn: 25,
    supervisorName: "Shihong Wong",
    supervisorAnimal: "lion",
  },
];

export const initialProjects: Project[] = [
  {
    id: 1,
    title: "Hiring Funnel Visualization Sprint",
    goal: "Students build a dashboard to visualise applicant-to-hire funnel data.",
    description:
      "Students propose and prototype a new way to visualize applicant-to-hire funnel data for non-technical hiring managers, using anonymized sample data provided by TalentBank.",
    projectArea: "Data Analytics",
    projectType: "Dashboard / Power BI Project",
    duration: "2 weeks",
    visibility: "collab",
    timelineMode: "fixed",
    targetUniversities: ["Asia Pacific University", "Sunway University"],
    targetAudience: ["Data Analytics students", "Software Engineering students"],
    skills: ["Data visualization", "Dashboard storytelling", "Prototyping"],
    tools: ["Power BI", "Figma"],
    deliverables: ["Dashboard prototype", "Presentation slides"],
    difficulty: "Intermediate",
    teamSize: "3-4 students",
    startDate: "2026-07-13",
    submissionDate: "2026-07-27",
    milestones: [
      { label: "Project brief published", date: "2026-06-20" },
      { label: "University team assigned", date: "2026-07-08" },
      { label: "Project kickoff", date: "2026-07-13" },
      { label: "Data exploration checkpoint", date: "2026-07-17" },
      { label: "Draft dashboard submission", date: "2026-07-22" },
      { label: "Final presentation", date: "2026-07-27" },
      { label: "Final submission", date: "2026-07-27" },
      { label: "Employer review", date: "2026-07-30" },
    ],
    status: "In Progress",
    createdAt: "2026-06-20T00:00:00.000Z",
    teams: [
      {
        id: 1,
        name: "APU DataViz Alpha",
        university: "Asia Pacific University",
        supervisor: "Dr. Tan Mei Yee",
        status: "Final Submitted",
        expectedSubmissionDate: "2026-07-27",
        submittedAt: "2026-07-27T00:00:00.000Z",
        submittedBy: "Mei Ling Tan",
        students: [
          { id: 1, name: "Mei Ling Tan", program: "Data Analytics", role: "Team Lead" },
          { id: 2, name: "Farid Rahman", program: "Software Engineering", role: "Dashboard Developer" },
          { id: 3, name: "Priya Sundaram", program: "Data Science", role: "Analyst" },
        ],
        files: [
          { name: "Power BI Dashboard.pbix", kind: "file" },
          { name: "Final Presentation.pptx", kind: "file" },
          { name: "Project Report.pdf", kind: "file" },
          { name: "Dashboard Preview Link", kind: "link" },
        ],
      },
      {
        id: 2,
        name: "APU Insight Builders",
        university: "Asia Pacific University",
        supervisor: "Dr. Tan Mei Yee",
        status: "In Progress",
        expectedSubmissionDate: "2026-07-27",
        students: [
          { id: 4, name: "Wei Jian Lim", program: "Business Analytics", role: "Presenter" },
          { id: 5, name: "Aaron Lim", program: "Data Analytics", role: "Dashboard Designer" },
        ],
        files: [],
      },
      {
        id: 3,
        name: "Sunway FunnelLab",
        university: "Sunway University",
        supervisor: "Mr. Raj Kumar",
        status: "Confirmed",
        expectedSubmissionDate: "2026-07-27",
        students: [
          { id: 6, name: "Alya Hassan", program: "Data Science", role: "Analyst" },
          { id: 7, name: "Daniel Wong", program: "Software Engineering", role: "Developer" },
        ],
        files: [],
      },
    ],
    feedback: {
      whatWorkedWell: "Strong dashboard storytelling and clear funnel visualisation from APU DataViz Alpha.",
      whatNeedsImprovement: "Improve filter controls and add clearer explanation for non-technical users.",
      finalOutcome: "",
    },
  },
  {
    id: 2,
    title: "Employer Brand Audit Capstone",
    goal: "Final-year students audit how TalentBank's public employer profile reads to candidates.",
    projectArea: "Digital Marketing",
    projectType: "Case Study Challenge",
    duration: "Ongoing",
    visibility: "collab",
    timelineMode: "ongoing",
    targetUniversities: ["Taylor's University"],
    targetAudience: ["Marketing students", "Final-year students"],
    skills: ["Brand audit", "Research", "Presentation"],
    tools: [],
    deliverables: ["Report", "Presentation slides"],
    difficulty: "Intermediate",
    milestones: [
      { label: "Initial research and stakeholder interviews", done: false },
      { label: "Draft findings review", done: false },
      { label: "Final report and presentation", done: false },
    ],
    status: "Draft",
    createdAt: "2026-07-01T00:00:00.000Z",
    teams: [],
  },
];

export const initialMembers: TeamMember[] = [
  {
    id: 1,
    name: "Shihong Wong",
    email: "admin@talentbank.com",
    role: "Super Admin",
    status: "Active",
    presence: "Online",
    focus: "Workspace owner",
    lastActive: "Now",
    password: "careeros",
    workAnimal: "lion",
  },
  {
    id: 2,
    name: "Sarah Lee",
    email: "sarah@talentbank.com",
    role: "Admin",
    status: "Active",
    presence: "Offline",
    focus: "Hiring operations",
    lastActive: "2h ago",
    password: "careeros",
    workAnimal: "dolphin",
  },
  {
    id: 3,
    name: "Nadia Lim",
    email: "nadia@talentbank.com",
    role: "User",
    status: "Active",
    presence: "Online",
    focus: "Candidate review",
    lastActive: "18m ago",
    password: "careeros",
    workAnimal: "ant",
  },
  {
    id: 4,
    name: "Victor Chen",
    email: "victor@talentbank.com",
    role: "User",
    status: "Active",
    presence: "Offline",
    focus: "Leadership visibility",
    lastActive: "Yesterday",
    password: "careeros",
    workAnimal: "eagle",
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: 1,
    jobId: 1,
    name: getCandidateLivingCv(1).name,
    title: getCandidateLivingCv(1).title,
    location: getCandidateLivingCv(1).location,
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 97,
    projectRelevance: 94,
    experience: 92,
    trajectory: 90,
    livingCv: "Verified",
    tags: [...getCandidateLivingCv(1).skills.technical.slice(0, 4), getCandidateLivingCv(1).direction],
    evidence: getCandidateLivingCv(1).employerEvidence,
    livingCvDetails: getCandidateLivingCv(1),
  },
  {
    id: 2,
    jobId: 1,
    name: "Irfan Rahman",
    title: "Senior PM, HR Tech",
    location: "Singapore",
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 91,
    projectRelevance: 89,
    experience: 88,
    trajectory: 86,
    livingCv: "Updated",
    tags: ["HR Tech", "AI workflows", "Enterprise"],
    evidence: getCandidateLivingCv(2).employerEvidence,
    livingCvDetails: getCandidateLivingCv(2),
  },
  {
    id: 3,
    jobId: 1,
    name: "Alya Hassan",
    title: "Growth Product Designer",
    location: "Kuala Lumpur",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 93,
    projectRelevance: 91,
    experience: 87,
    trajectory: 92,
    livingCv: "Verified",
    tags: ["Activation", "Design systems", "Research"],
    evidence: getCandidateLivingCv(3).employerEvidence,
    livingCvDetails: getCandidateLivingCv(3),
  },
  {
    id: 4,
    jobId: 1,
    name: "Daniel Ong",
    title: "Principal Product Manager",
    location: "Remote",
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 82,
    projectRelevance: 84,
    experience: 90,
    trajectory: 83,
    livingCv: "Stale",
    tags: ["0-1", "Discovery", "PLG"],
    evidence: getCandidateLivingCv(4).employerEvidence,
    livingCvDetails: getCandidateLivingCv(4),
  },
  {
    id: 5,
    jobId: 2,
    name: getCandidateLivingCv(5).name,
    title: getCandidateLivingCv(5).title,
    location: getCandidateLivingCv(5).location,
    source: "Applied",
    stage: "Shortlisted",
    type: "Shortlisted",
    status: "Waiting",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 91,
    projectRelevance: 94,
    experience: 88,
    trajectory: 89,
    livingCv: "Verified",
    tags: [...getCandidateLivingCv(5).skills.technical.slice(0, 4), getCandidateLivingCv(5).direction],
    evidence: getCandidateLivingCv(5).employerEvidence,
    livingCvDetails: getCandidateLivingCv(5),
  },
  {
    id: 6,
    jobId: 2,
    name: getCandidateLivingCv(6).name,
    title: getCandidateLivingCv(6).title,
    location: getCandidateLivingCv(6).location,
    source: "Applied",
    stage: "New",
    type: "Applied",
    status: "New",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 89,
    projectRelevance: 96,
    experience: 86,
    trajectory: 91,
    livingCv: "Updated",
    tags: [...getCandidateLivingCv(6).skills.technical.slice(0, 4), getCandidateLivingCv(6).direction],
    evidence: getCandidateLivingCv(6).employerEvidence,
    livingCvDetails: getCandidateLivingCv(6),
  },
  {
    id: 7,
    jobId: 2,
    name: getCandidateLivingCv(7).name,
    title: getCandidateLivingCv(7).title,
    location: getCandidateLivingCv(7).location,
    source: "Applied",
    stage: "Invited",
    type: "Shortlisted",
    status: "Invited",
    appliedToJob: true,
    pastSecondStage: false,
    skillFit: 84,
    projectRelevance: 88,
    experience: 92,
    trajectory: 82,
    livingCv: "Verified",
    tags: [...getCandidateLivingCv(7).skills.technical.slice(0, 4), getCandidateLivingCv(7).direction],
    evidence: getCandidateLivingCv(7).employerEvidence,
    livingCvDetails: getCandidateLivingCv(7),
  },
  {
    id: 8,
    jobId: 2,
    name: getCandidateLivingCv(8).name,
    title: getCandidateLivingCv(8).title,
    location: getCandidateLivingCv(8).location,
    source: "Potential",
    stage: "New",
    type: "Potential",
    status: "New",
    appliedToJob: false,
    pastSecondStage: true,
    skillFit: 83,
    projectRelevance: 86,
    experience: 79,
    trajectory: 90,
    livingCv: "Updated",
    tags: [...getCandidateLivingCv(8).skills.technical.slice(0, 4), getCandidateLivingCv(8).direction],
    evidence: getCandidateLivingCv(8).employerEvidence,
    livingCvDetails: getCandidateLivingCv(8),
  },
];

export const initialHiringSettings: HiringSettings = {
  scoreWeights: {
    skill: 35,
    project: 30,
    experience: 20,
    trajectory: 15,
  },
  expiry: {
    countdown: true,
    promptResult: true,
    stayOpenAfterHire: true,
    autoCloseAfterHireDays: 30,
  },
  validation: {
    duplicateTitle: true,
    requireDepartment: true,
    logActions: true,
  },
  templates: {
    interview: {
      subject: "Next stage invitation: {{stageType}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nThank you for your interest in the {{role}} role. We would like to invite you to the next stage: {{stageType}}.\n\nTime: {{selectedSlot}}\nLocation: {{meetingLink}}\n\nPlease bring any questions about the team, role scope, and hiring process.\n\nBest,\n{{sender}}",
      includeLogo: true,
      stageType: "Online interview",
      dateTime: "{{selectedSlot}}",
      location: "{{meetingLink}}",
    },
    hired: {
      subject: "Hiring update from {{company}}",
      sender: "{{company}} Hiring Team",
      body:
        "Hi {{firstName}},\n\nCongratulations. We are excited to move forward with you for the {{role}} role at {{company}}.\n\nNext step: {{nextStep}}.\n\nProposed start date: {{startDate}}.\n\nBest,\n{{sender}}",
      includeLogo: true,
      startDate: "{{startDate}}",
      nextStep: "{{onboardingStep}}",
    },
  },
};

export const initialActivity: ActivityEvent[] = [
  { id: 1, label: "Maya Tan shortlisted for Senior Product Lead", time: "2h ago", tone: "pink" },
  { id: 2, label: "Alya Hassan flagged for re-engagement", time: "Today", tone: "amber" },
  { id: 3, label: "Senior Product Lead expires in 18 days", time: "Job timer", tone: "zinc" },
];

export const navItems: Array<{ page: Page; label: string }> = [
  { page: "dashboard", label: "Dashboard" },
  { page: "jobs", label: "Jobs" },
  { page: "projects", label: "Projects" },
  { page: "team", label: "Team" },
  { page: "profile", label: "Profile" },
  { page: "settings", label: "Settings" },
];
